name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  save-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Save kube-apiserver
        run: docker pull opengeminidb/opengemini-server:latest; docker save opengeminidb/opengemini-server:latest -o opengemini-latest.tar.gz
      - name: Release
        uses: shoothzj/latest-release-action@v1
        with:
          tag_name: latest
          release_name: latest
          files: opengemini-latest.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
